import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopMenu from "@/components/TopMenu";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/authOptions";
import NextAuthProvider from "@/providers/NextAuthProvider";
import getUserProfile from "@/libs/getUserProfile";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);  
  let user;
  let role = "";
  if (session?.user.token) {
    user = await getUserProfile(session.user.token);
  }
  if (user) {
    role = user.data.role;
  }

  return (
    <html lang="en">
      <body className="bg-white text-black font-mono overflow-hidden">
        <NextAuthProvider>
          <TopMenu />

          {/* Push content down below fixed TopMenu (assumed height 80px) */}
          <div className="pt-[60px] flex overflow-hidden">
            {role === "admin" && (
              <div className="w-[300px]">
                <Sidebar />
              </div>
            )}

            {/* Content area */}
            <div className={`flex-1  ${role === "admin" ? "" : "w-full"}`}>
              {children}
            </div>
          </div>
        </NextAuthProvider>
      </body>
    </html>
  );
}
